name: Build Command
on:
  repository_dispatch:
    types: [build-command]
jobs:
  build_ci:
    name: build ci
    runs-on: ubuntu-16.04
    timeout-minutes: 50
    env:
      BRANCH: "${{ github.event.client_payload.pull_request.head.ref }}-ci"
      TARGET_DIR: tmp_op_ci
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
      - name: Prepare release files
        run: |
          chmod +x release/build_release_ci.sh
          ./release/build_release_ci.sh
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
          directory: ${{ env.TARGET_DIR }}
          force: true