name: build openpilot
on:
  push:
env:
  RUN: docker run --shm-size 1G --rm tmppilot /bin/sh -c
  UNIT_TEST: coverage run --append -m unittest discover
  BUILD: |
      docker pull $(grep -ioP '(?<=^from)\s+\S+' Dockerfile.openpilot) || true
      docker pull docker.io/commaai/openpilotci:latest || true
      docker build --cache-from docker.io/commaai/openpilotci:latest -t tmppilot -f Dockerfile.openpilot .
jobs:
  build_release:
    name: build release
    runs-on: ubuntu-16.04
    timeout-minutes: 50
    env:
      TEST_DIR: tmppilot
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Strip non-release files
      run: |
        mkdir $TEST_DIR
        cp -pR --parents $(cat release/files_common) $TEST_DIR
        cp Dockerfile.openpilot $TEST_DIR
        # need this to build on x86
        cp -pR --parents phonelibs/libyuv phonelibs/snpe \
                         external/bin selfdrive/modeld/runners $TEST_DIR
        # need these so docker copy won't fail
        cp Pipfile Pipfile.lock .pylintrc .coveragerc-app .pre-commit-config.yaml $TEST_DIR
        cd $TEST_DIR
        mkdir laika laika_repo tools
    - name: Build Docker image
      run: cd $TEST_DIR && eval "$BUILD"
    - name: Build openpilot and run quick check
      run: |
          $RUN "cd /tmp/openpilot && \
                scons -j$(nproc) && \
                $UNIT_TEST selfdrive/car"