name: Release Command
on:
  repository_dispatch:
    types: [release-command]
jobs:
  release:
    runs-on: ubuntu-latest
    #if: ${{ PR.mergeble }}
    env:
      PR_BASE: ${{ github.event.client_payload.pull_request.base.sha }}
      PR_HEAD: ${{ github.event.client_payload.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.client_payload.pull_request.number }}
      PR_TITLE: ${{ github.event.client_payload.pull_request.title }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Cherry pick commits
        run: |
          git config --global user.email "$GITBOT_EMAIL"
          git config --global user.name "$GITHUB_ACTOR"
          git log --cherry --format="%h" "$PR_BASE".."$PR_HEAD" | git cherry-pick --stdin -X ours --allow-empty --keep-redundant-commits
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          commit-message: 'release(#"$PR_NUMBER"): "$PR_TITLE"'
          branch: 'release-"$PR_NUMBER"'
          title: 'Release -- "$PR_TITLE"'
          body: 'Applying commits from PR#"$PR_NUMBER"'



