name: Release Command
on:
  repository_dispatch:
    types: [release-command]
jobs:
  release:
    runs-on: ubuntu-latest
    #if: ${{ PR.mergeble }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: r2++
      - name: Cherry pick commits
        run: |
          git config --global user.email "$GITBOT_EMAIL"
          git config --global user.name "$GITHUB_ACTOR"
          git fetch
          git log ${{ github.event.client_payload.pull_request.base.ref }}..${{ github.event.client_payload.pull_request.head.ref }} | git cherry-pick --stdin
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          commit-message: release(#${{ github.event.client_payload.pull_request.number }}):${{ github.event.client_payload.pull_request.title }}
          branch: release-${{ github.event.client_payload.pull_request.number }}
          title: Relase -- ${{ github.event.client_payload.pull_request.title }}
          body: Applying commits from PR#${{ github.event.client_payload.pull_request.number }}



